######################################################################
##
## Filename: test_string_detectore_mode1.udo
## Created on: Fri Nov 06 10:28:18 AM Iran Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
